events {}

http {
    server {
        listen 8080;

        root  /var/www/adminer;
        index index.php;

        location / {
            try_files $uri $uri/ =404;
        }

        # Passe les fichiers .php à PHP-FPM
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        }
    }
}