# Pas d'accès anonyme
anonymous_enable=NO

# Autorise les utilisateurs système à se connecter
local_enable=YES

# Autorise l'upload et la modification de fichiers
write_enable=YES

# L'utilisateur reste bloqué dans son dossier home (sécurité)
chroot_local_user=YES
allow_writeable_chroot=YES

# Mode passif : nécessaire pour les connexions depuis l'extérieur du réseau Docker
pasv_enable=YES
pasv_min_port=21000
pasv_max_port=21010
pasv_address=127.0.0.1

# Lance en foreground pour rester en PID 1
background=NO